using Aero.MDH.DatabaseAccess.BusinessEntities.Savers.Base;

namespace Aero.MDH.DatabaseAccess.BusinessEntities.Savers.Company;

public class CompanyGlobalIdSaver : GlobalIdSaver<CompanyBusinessEntity>, ICompanyGlobalIdSaver
{
    protected override string BusinessEntityType => "company";

    public CompanyGlobalIdSaver(AutoGenerated.MdhDbContext mdhDbContext) : base(mdhDbContext)
    {
    }
}