using Aero.MDH.DatabaseAccess.BusinessEntities.DataServices.Base;

namespace Aero.MDH.DatabaseAccess.BusinessEntities.Savers.Company;

public class CompanyIdSaver : ICompanyIdSaver
{
    public Task<SaveResult<CompanyBusinessEntity>> SaveAsync(List<CompanyBusinessEntity> entities,
        AutoGenerated.MdhDbContext dbContext,
        CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }
}