using Aero.MDH.DatabaseAccess.BusinessEntities.Savers.Base;
using Microsoft.EntityFrameworkCore;
using CompanyDatum = Aero.MDH.DatabaseAccess.AutoGenerated.Models.CompanyDatum;

namespace Aero.MDH.DatabaseAccess.BusinessEntities.Savers.Company;

public class CompanyDataSaver : DataModelSaver<CompanyBusinessEntity, CompanyDatum>, ICompanyDataSaver
{
    public CompanyDataSaver(AutoGenerated.MdhDbContext dbContext) : base(dbContext)
    {
    }

    protected override DbSet<CompanyDatum> GetDbSet()
    {
        return DbContext.CompanyData;
    }
}