Set-Location -Path $PSScriptRoot

dotnet ef dbcontext scaffold --project .\Aero.MDH.DatabaseAccess.csproj --startup-project .\Aero.MDH.DatabaseAccess.csproj --configuration Debug "Server=(localdb)\MSSQLLocalDB;Database=MDH" Microsoft.EntityFrameworkCore.SqlServer --context MdhDbContext --context-dir AutoGenerated --force --output-dir AutoGenerated/Models --schema dbo --namespace Aero.MDH.DatabaseAccess.Models --context-namespace Aero.MDH.DatabaseAccess --no-onconfiguring

git add .\AutoGenerated\*