Set-Location -Path $PSScriptRoot

dotnet ef dbcontext scaffold --project .\MDH.DatabaseAccess.csproj --startup-project .\MDH.DatabaseAccess.csproj --configuration Debug "Server=(localdb)\MSSQLLocalDB;Database=MDH" Microsoft.EntityFrameworkCore.SqlServer --context MdhDbContext --context-dir AutoGenerated --force --output-dir AutoGenerated/Models --schema dbo --namespace MDH.DatabaseAccess.Models --context-namespace MDH.DatabaseAccess --no-onconfiguring

git add ..\AutoGenerated\*