using Aero.MDH.DatabaseAccess.BusinessEntities.Base;
using Aero.MDH.DatabaseAccess.BusinessEntities.Savers.Base;

namespace Aero.MDH.DatabaseAccess.BusinessEntities.DataServices.Base;

public abstract class AbstractSaveRequest<T> where T : AbstractBusinessEntity
{
    private readonly ICollection<T> _entities;
    protected readonly List<IBusinessEntitySaver<T>> Savers = new();
    private readonly AutoGenerated.MdhDbContext _dbContext;
    private readonly IGlobalIdSaver<T> _globalIdSaver;
    private readonly ICompanyIdSaverddd _companyIdSaver;

    protected AbstractSaveRequest(IGlobalIdSaver<T> globalIdSaver, ICollection<T> entities, AutoGenerated.MdhDbContext dbContext)
    {
        _entities = entities;
        _dbContext = dbContext;
        _globalIdSaver = globalIdSaver;
    }

    public async Task<SaveResult<T>> SaveAsync(CancellationToken cancellationToken = default)
    {
        var businessEntitiesToCreate = _entities.Where(e => e.Id == 0).ToList();

        if (businessEntitiesToCreate.Any())
        {
            await _globalIdSaver.CreateGlobalIdAsync(businessEntitiesToCreate);
        }
        
        foreach (var saver in Savers)
        {
            await saver.SaveAsync(_entities.ToList(), _dbContext, cancellationToken);
        }

        await _dbContext.SaveChangesAsync(cancellationToken);
        return new SaveResult<T>(true, savedEntities: _entities.ToList());
    }
}