using Aero.MDH.DatabaseAccess.BusinessEntities.Base;

namespace Aero.MDH.DatabaseAccess.BusinessEntities.DataServices.Base;

public interface IBusinessEntitySaver<T> where T : AbstractBusinessEntity
{
    Task<SaveResult<T>> SaveAsync(List<T> entities, AutoGenerated.MdhDbContext dbContext, CancellationToken cancellationToken);
}